### ISSUE TITLE
Action failed but it was marked as successful

### ISSUE THREAD

**Issue by TaiSHiNet** [webfactory/create-aws-codedeploy-deployment#10]
While deploying, I had this error (appspec.yml does exist though) and the action was marked as successful.

If you need more code let me know. Deploy is running on a self-hosted Amazon Linux 2 VM
```
(node:20704) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './appspec.yml'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at fetchBranchConfig (/home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:23:27)
    at Object.exports.createDeployment (/home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:43:26)
    at /home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:201:16
    at Object.2932 (/home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:203:3)
    at __webpack_require__ (/home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:50113:43)
    at /home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:50130:18
    at Object.<anonymous> (/home/ec2-user/actions-runner/_work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:50131:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
(node:20704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TaiSHiNet** [comment]
For future reference about the missing appspec: [this](https://twitter.com/nixcraft/status/1435170137154285573)

I was being frupid and didn't add the `actions/checkout@v2` action

The build being marked as successful issue remains

Edited due to missing info + closed issue by mistake
