### ISSUE TITLE
 AccessDeniedException: Cross-account pass role is not allowed.

### ISSUE THREAD

**Issue by dschmidtadv** [webfactory/create-aws-codedeploy-deployment#11]
The following error is rendered when running the action:
`(node:1789) UnhandledPromiseRejectionWarning: AccessDeniedException: Cross-account pass role is not allowed.
    at Request.extractError (/home/runner/work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:23887:27)
    at Request.callListeners (/home/runner/work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.2/dist/index.js:26184:20)`
I previously used the same repo with a different AWS account, but access information has been updated.

**Comment by TaiSHiNet** [comment]
Could you share your config? 
How are you setting up the credentials?

**Comment by mpdude** [comment]
@dschmidtadv Is this still an issue for you?
